config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  resources :products do
    get :cms, on: :collection
  end

  resources :product_items, only: [:create, :delete, :destroy]
  patch 'product_items/:id/add' => 'product_items#add_quantity', as: 'product_item_add'
  patch 'product_items/:id/reduce' => 'product_items#reduce_quantity', as: 'product_item_reduce'
  resources :carts, only: [:show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :product_items, dependent: :destroy

  def product_ids
    self.product_items.map(&:product_id)
  end

  def total_quantity
    self.product_items.sum(&:quantity)
  end

  def total
    sum = 0
    product_items.each do |product_item|
      sum += product_item.total_price
    end
    sum
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_items
end

app/models/product_item.rb
class ProductItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def total_price
    quantity * product.price
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_cart

  def set_cart
    if session[:cart_id]
      cart = Cart.find_by(id: session[:cart_id])
      cart.present? ? (@current_cart = cart) : (session[:cart_id] = nil)
    end
    return unless session[:cart_id].nil?

    @current_cart = Cart.create
    session[:cart_id] = @current_cart.id
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/controllers/product_items_controller.rb
class ProductItemsController < ApplicationController
  before_action :get_item, only: [:add_quantity, :reduce_quantity]

  def create
    chosen_product = Product.find(params[:product_id])
    add_items_to_cart(chosen_product, params[:quantity].to_i)
    respond_to do |format|
      if @product_item.save!
        format.html { redirect_back(fallback_location: @current_cart) }
        format.js
      else
        format.html { render :new, notice: 'Error adding product to basket!' }
      end
    end
  end

  def add_quantity
    @product_item.quantity += 1
    @product_item.save
    redirect_to cart_path(@current_cart)
  end

  def reduce_quantity
    if @product_item.quantity > 1
      @product_item.quantity -= 1
      @product_item.save
      redirect_to cart_path(@current_cart)
    elsif @product_item.quantity == 1
      destroy
    end
  end

  def delete; end

  def destroy
    item = ProductItem.find(params[:id])
    item.destroy
    redirect_to cart_path(@current_cart)
  end

  private

  def add_items_to_cart(chosen_product, quantity = 1)
    if @current_cart.product_ids.include?(chosen_product.id)
      @product_item = @current_cart.product_items.find_by(product_id: chosen_product)
      @product_item.quantity += quantity
    else
      @product_item = ProductItem.new
      @product_item.cart = @current_cart
      @product_item.product = chosen_product
      @product_item.quantity = quantity
    end
  end

  def get_item
    @product_item = ProductItem.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :get_product, only: %i[show edit update destroy]

  def index
    @products = Product.all
  end

  def show; end

  def cms
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render :new
    end
  end

  def edit; end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to cms_products_url
  end

  private

  def get_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :image_url, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<div class="bg-light py-3">
  <div class="container">
    <div class="row">
      <div class="col-md-12 mb-0"><a href="<%= root_path %>">Home</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">Cart</strong></div>
    </div>
  </div>
</div>

<div class="site-section">
  <div class="container">
    <div class="row mb-5">
      <form class="col-md-12" method="post">
        <div class="site-blocks-table">
          <table class="table table-bordered">
            <thead>
            <tr>
              <th class="product-thumbnail">Image</th>
              <th class="product-name">Product</th>
              <th class="product-price">Price</th>
              <th class="product-quantity">Quantity</th>
              <th class="product-total">Total</th>
              <th class="product-remove">Remove</th>
            </tr>
            </thead>
            <tbody>
            <% @cart.product_items.each do |item| %>
              <tr>
                <td class="product-thumbnail">
                  <img src="<%= item.product.image_url %>" alt="Image" class="img-fluid">
                </td>
                <td class="product-name">
                  <h2 class="h5 text-black"><%= item.product.name %></h2>
                </td>
                <td>$<%= item.product.price %></td>
                <td>
                  <div class="input-group mb-3" style="max-width: 120px;">
                    <div class="input-group-prepend">
                      <%= button_to raw('&minus;'), product_item_reduce_path(item), method: :patch, class: "btn btn-outline-primary"%>
                    </div>
                    <input type="text" class="form-control text-center" value="<%= item.quantity %>" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                    <div class="input-group-append">
                      <%= button_to raw('&plus;'), product_item_add_path(item), method: :patch, class: "btn btn-outline-primary"%>
                    </div>
                  </div>

                </td>
                <td class="item-total-price">$<%= item.product.price * item.quantity %></td>
                <td><%= button_to "X", product_item_path(item), method: :delete, data: {confirm: "Are you sure?"} , class: "btn btn-danger height-auto btn-sm"%></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </form>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="row mb-5">
          <div class="col-md-6">
            <%= button_to "Continue Shopping", root_path , class: "btn btn-outline-primary btn-sm btn-block" , method: :get%>
          </div>
          <% if @current_cart.product_items.count > 0  %>
            <div class="col-sm-12 col-md-6">
              <%= button_to "Empty cart", cart_path(@current_cart), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-lg btn-block btn-danger text-uppercase"%>
            </div>
          <% end %>
        </div>
        <div class="row">
          <div class="col-md-12">
            <label class="text-black h4" for="coupon">Coupon</label>
            <p>Enter your coupon code if you have one.</p>
          </div>
          <div class="col-md-8 mb-3 mb-md-0">
            <input type="text" class="form-control py-3" id="coupon" placeholder="Coupon Code">
          </div>
          <div class="col-md-4">
            <button class="btn btn-primary btn-sm px-4">Apply Coupon</button>
          </div>
        </div>
      </div>
      <div class="col-md-6 pl-5">
        <div class="row justify-content-end">
          <div class="col-md-7">
            <div class="row">
              <div class="col-md-12 text-right border-bottom mb-5">
                <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
              </div>
            </div>
            <div class="row mb-5">
              <div class="col-md-6">
                <span class="text-black">Total</span>
              </div>
              <div class="col-md-6 text-right">
                <strong class="text-black">$<%= @cart.total %></strong>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <button class="btn btn-primary btn-lg btn-block" onclick="window.location='checkout.html'">Proceed To Checkout</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsGirlDemo</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700" rel="stylesheet">
  <link rel="stylesheet" href="/fonts/icomoon/style.css">

  <link rel="stylesheet" href="/css/bootstrap.min.css">
  <link rel="stylesheet" href="/css/magnific-popup.css">
  <link rel="stylesheet" href="/css/jquery-ui.css">
  <link rel="stylesheet" href="/css/owl.carousel.min.css">
  <link rel="stylesheet" href="/css/owl.theme.default.min.css">


  <link rel="stylesheet" href="/css/aos.css">

  <link rel="stylesheet" href="/css/style.css">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="/js/jquery-3.2.1.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="site-wrap">
  <div class="site-navbar bg-white py-2">

    <div class="search-wrap">
      <div class="container">
        <a href="#" class="search-close js-search-close"><span class="icon-close2"></span></a>
        <form action="#" method="post">
          <input type="text" class="form-control" placeholder="Search keyword and hit enter...">
        </form>
      </div>
    </div>

    <div class="container">
      <div class="d-flex align-items-center justify-content-between">
        <div class="logo">
          <div class="site-logo">
            <a href="<%= root_path %>" class="js-logo-clone">Dealers</a>
          </div>
        </div>
        <div class="icons">
          <a href="#" class="icons-btn d-inline-block js-search-open"><span class="icon-search"></span></a>
          <a href="#" class="icons-btn d-inline-block"><span class="icon-heart-o"></span></a>
          <a href="<%= cart_path(@current_cart) %>" class="icons-btn d-inline-block bag">
            <span class="icon-shopping-bag"></span>
            <% if @current_cart.total_quantity > 0 %>
              <span class="number"><%= @current_cart.total_quantity %></span>
            <% end %>
          </a>
          <a href="#" class="site-menu-toggle js-menu-toggle ml-3 d-inline-block d-lg-none"><span class="icon-menu"></span></a>
        </div>
      </div>
    </div>
  </div>
  <br/>
  <%= yield %>
</div>
<footer class="site-footer custom-border-top">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">

        <div class="block-7">
          <h3 class="footer-heading mb-4">About Us</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius quae reiciendis distinctio voluptates sed dolorum excepturi iure eaque, aut unde.</p>
        </div>
        <div class="block-7">
          <form action="#" method="post">
            <label for="email_subscribe" class="footer-heading">Subscribe</label>
            <div class="form-group">
              <input type="text" class="form-control py-4" id="email_subscribe" placeholder="Email">
              <input type="submit" class="btn btn-sm btn-primary" value="Send">
            </div>
          </form>
        </div>
      </div>
      <div class="col-lg-5 ml-auto mb-5 mb-lg-0">
        <div class="row">
          <div class="col-md-12">
            <h3 class="footer-heading mb-4">Quick Links</h3>
          </div>
          <div class="col-md-6 col-lg-4">
            <ul class="list-unstyled">
              <li><a href="#">Sell online</a></li>
              <li><a href="#">Features</a></li>
              <li><a href="#">Shopping cart</a></li>
              <li><a href="#">Store builder</a></li>
            </ul>
          </div>
          <div class="col-md-6 col-lg-4">
            <ul class="list-unstyled">
              <li><a href="#">Mobile commerce</a></li>
              <li><a href="#">Dropshipping</a></li>
              <li><a href="#">Website development</a></li>
            </ul>
          </div>
          <div class="col-md-6 col-lg-4">
            <ul class="list-unstyled">
              <li><a href="#">Point of sale</a></li>
              <li><a href="#">Hardware</a></li>
              <li><a href="#">Software</a></li>
            </ul>
          </div>
        </div>
      </div>

      <div class="col-md-6 col-lg-3">
        <div class="block-5 mb-5">
          <h3 class="footer-heading mb-4">Contact Info</h3>
          <ul class="list-unstyled">
            <li class="address">203 Fake St. Mountain View, San Francisco, California, USA</li>
            <li class="phone"><a href="tel://23923929210">+2 392 3929 210</a></li>
            <li class="email">emailaddress@domain.com</li>
          </ul>
        </div>


      </div>
    </div>
    <div class="row pt-5 mt-5 text-center">
      <div class="col-md-12">
        <p>
          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          Copyright &copy;2019 All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" class="text-primary">Colorlib</a>
          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        </p>
      </div>

    </div>
  </div>
</footer>
<script src="/js/jquery-ui.js"></script>
<script src="/js/popper.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/owl.carousel.min.js"></script>
<script src="/js/jquery.magnific-popup.min.js"></script>
<script src="/js/aos.js"></script>

<script src="/js/main.js"></script>
</body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <div class="form-group">
    <% if product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %>
          prohibited this product from being saved:</h2>

        <ul>
          <% product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-input", id: :product_name %>
    </div>

    <div>
      <%= form.label :description, class: "form-label" %>
      <%= form.text_field :description, class: "form-input", id: :product_description, :size => "50x10"%>
    </div>

    <div>
      <%= form.label :price, class: "form-label" %>
      <%= form.text_field :price, class: "form-input", id: :product_price %>
    </div>

    <div>
      <%= form.label :image_url, class: "form-label" %>
      <%= form.text_field :image_url, class: "form-input", id: :product_image %>
    </div>

    <div>
      <%= form.submit "Submit", class: "btn btn-primary rounded-0" %>
    </div>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="col-6 col-md-6 col-lg-4">
  <a href="<%= products_path + '/' + product.id.to_s %>" class="item">
    <img src="<%= product.image_url %>" alt="Image" class="img-fluid">
    <div class="item-info">
      <h3><%= product.name %></h3>
      <span class="collection d-block"><%= product.description %></span>
      <strong class="price">$<%= product.price %></strong>
    </div>
  </a>
</div>

app/views/products/_product_cms.html.erb
<div class="col-6 col-md-6 col-lg-4">
  <a href="<%= products_path + '/' + product.id.to_s %>" class="item">
    <img src="<%= product.image_url %>" alt="Image" class="img-fluid">
    <div class="item-info">
      <h3><%= product.name %></h3>
      <span class="collection d-block"><%= product.description %></span>
      <strong class="price">$<%= product.price %></strong>
    </div>
    <%= link_to("Edit", edit_product_path(product), class: "btn btn-warning rounded-0") %>
    <%= link_to("Delete", product_path(product),
                class: "btn btn-danger rounded-0",
                method: :delete,
                data: {confirm: "Are you sure you want to delete? This action can't be undone."} )
    %>
  </a>
</div>

app/views/products/cms.html.erb
<div class="products-wrap border-top-0">
  <div class="container-fluid">
    <%= link_to("New Product", new_product_path, class: "btn btn-primary rounded-0") %>
    <div class="row no-gutters products">
      <% @products.each do |product| %>
        <%= render 'product_cms', product: product %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<div class="product_image_area section_gap_bottom_custom">
  <div class="container">
    <h1>Editing Product</h1>
    <%= render 'form', product: @product %>
    <%= link_to 'Show', @product %>
  </div>
</div>

app/views/products/index.html.erb
<div class="site-blocks-cover" data-aos="fade">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-5 text-center">
        <div class="featured-hero-product w-100">
          <h1 class="mb-2">Madewell</h1>
          <h4>Summer Collection</h4>
          <div class="price mt-3 mb-5"><strong>1,499</strong> <del>$1,999</del></div>
          <p>
            <a href="#products" class="btn btn-outline-primary rounded-0">Shop Now</a>
            <a href="#products" class="btn btn-primary rounded-0">Shop Now</a>
          </p>
        </div>
      </div>
      <div class="col-lg-7 align-self-end text-center text-lg-right">
        <img src="images/new/person_transparent.png" alt="Image" class="img-fluid img-1">
      </div>
    </div>
  </div>
</div>

<div class="products-wrap border-top-0" id="products">
  <div class="container-fluid">
    <div class="row no-gutters products">
      <% @products.each do |product| %>
        <%= render partial: product %>
      <% end %>
    </div>
  </div>
</div>

<div class="site-blocks-cover inner-page py-5"  data-aos="fade">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 ml-auto order-lg-2 align-self-start">
        <div class="site-block-cover-content">
          <h2 class="sub-title">#New Summer Collection 2019</h2>
          <h1>New Denim Coat</h1>
          <p><a href="#" class="btn btn-black rounded-0">Shop Now</a></p>
        </div>
      </div>
      <div class="col-lg-6 order-1 align-self-end">
        <img src="images/model_5.png" alt="Image" class="img-fluid">
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="product_image_area section_gap_bottom_custom">
  <div class="container">
    <h1>New Product</h1>
    <%= render 'form', product: @product %>
  </div>
</div>

app/views/products/show.html.erb
<div class="site-section">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="border">
          <img src="<%= @product.image_url %>" alt="Image" class="img-fluid">
        </div>
      </div>
      <div class="col-md-6">
        <h2 class="text-black"><%= @product.name %></h2>
        <p><%= @product.description %></p>
        <p><strong class="text-primary h4">$<%= @product.price %></strong></p>
        <%= form_with(model: ProductItem.new, local: true) do |form| %>
          <input type="text" name="product_id"
                 value="<%= @product.id %>"
                 style="display: none"/>
          <div class="mb-5">
            <div class="input-group mb-3" style="max-width: 120px;">
              <div class="input-group-prepend">
                <button class="btn btn-outline-primary js-btn-minus" type="button">&minus;</button>
              </div>
              <input type="text" name="quantity" class="form-control text-center" value="1" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
              <div class="input-group-append">
                <button class="btn btn-outline-primary js-btn-plus" type="button">&plus;</button>
              </div>
            </div>
          </div>
          <%= form.submit "Add To Cart", class: "buy-now btn btn-sm height-auto px-4 py-3 btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>